# Generated by Django 4.2.17 on 2025-06-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceOrganizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=200)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('operation_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('payer_inn', models.CharField(max_length=200)),
                ('document_number', models.CharField(max_length=200)),
                ('document_date', models.DateTimeField()),
            ],
        ),
    ]
